title: trans@blahaj
description: A collection of resources for the trans@lemmy.blahaj.zone community
theme: just-the-docs

url: https://trans-blahaj-zone.github.io

nav_external_links:
  - title: /c/trans
    url: https://lemmy.blahaj.zone/c/trans

callouts:
  crisis:
    color: red
  important:
    color: yellow
  warning:
    color: yellow
  important-warning:
    color: red
  more:
    title: Further Reading
    color: grey-dk
  meta:
    title: Meta
    color: grey-dk

aux_links:
  /c/trans: https://lemmy.blahaj.zone/c/trans
