blank_issues_enabled: true
contact_links:
  - name: "💡 Content Request"
    url: "https://github.com/trans-blahaj-lemmy/trans-blahaj-lemmy.github.io/discussions/new?category=ideas"
    about: "Suggest new content or enhancement."